name: Deploy Master Branch
on:
    push:
        branches:
            - main
jobs:
    build:
        name: Build Solid site
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setting up pnpm
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.0.2
                  run_install: true
            - name: Building Project
              run: pnpm build
              env:
                  VITE_API_TOKEN: ${{ secrets.VITE_API_TOKEN }}
                  VITE_REDIRECT_URI: ${{ secrets.VITE_REDIRECT_URI }}
            - name: Deploying site
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist
