name: Deploy Master Branch
on:
    push:
        branches:
            - master
jobs:
    build:
        name: Build Solid site
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - name: Install dependencies
              run: pnpm i
            - name: Build
              run: pnpm build
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.ACCESS_TOKEN }}
                  publish_dir: ./dist
